

logging:
  level:
    org:
      springframework:
        jdbc:
          core: trace
spring:
  datasource:
    url: jdbc:mysql://${url}?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
